# Generated by Django 5.0.1 on 2024-02-06 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='subject',
        ),
        migrations.AddField(
            model_name='users',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='bp207001@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='major',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
