# Generated by Django 2.2.28 on 2024-02-10 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240210_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
