# Generated by Django 2.2.28 on 2024-02-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0007_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('age', models.CharField(blank=True, max_length=3)),
                ('email', models.EmailField(max_length=50)),
                ('major', models.CharField(blank=True, max_length=75, null=True)),
                ('about', models.TextField(blank=True, max_length=1000, null=True)),
                ('role', models.CharField(default=False, max_length=50)),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='profile_pictures/')),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
